server:
  port: 8080
  error:
    include-message: always # Útil para Debug mas mascararemos erros globais em produção

spring:
  application:
    name: eventos-saas
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/marcador_eventos}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:121546}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Alterado para não perder os dados!
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuração do nosso Token JWT (Exemplo simples com validade de 24 horas)
api:
  security:
    token:
      secret: ${JWT_SECRET:S3cr3tVeryL0ngT0kenForSaaSAuth3nticat10nEvent0sA2F9R8X}
      expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
